var express = require('express');
var app = express();

app.get('/', function (req, res) {
  res.send("TVRoZAAAAAYAAQAEADBNVHJrAAAAWgD/AyJBbGxleXdheSAtIFRpdGxlIFNjcmVlbiAoR2FtZSBCb3kpAP8BF3NlcXVlbmNlZCBieSBDaHJpcyBSZWFkAP9YBAQCGAgA/1kCAAAA/1EDBWKtAP8vAE1UcmsAAAEpAMAMgSiQSX8YSQAAR38YRwAARX8MRQAASX8YSQAASX8MSQAMSX8MSQAAR38YRwAARX8YRQAYSn8YSgAAR38YRwAARX8MRQAASn8YSgAASn8MSgAMSn8MSgAAR38YRwAARX8YRQAYSX8YSQAAR38YRwAARX8MRQAASX8YSQAASX8MSQAMSX8MSQAAR38MRwAARX8MRQAASX8MSQAASn8YSgAMSn8YSgAAR38MRwAARX8MRQAASX8MSQAASn8YSgAATH8YTAAATn8MTgAASn8YSgAwSX8YSQAAR38MRwAARX8MRQAAR38MRwAASX8YSQAMSX8YSQAATX8MTQAATn8YTgAASn8YSgAMSn8MSgAAR38YRwAARX8MRQAASX8YSQAASn8YSgAA/y8ATVRyawAAAM8AwQwAkTR/DDQAADR/GDQAADR/DDQAADV/DDUADDZ/DDYADDd/JDcADD1/GD0AGD1/GD0AGD1/GD0AGD1/GD0AGDJ/GDIAGDJ/GDIAGDJ/GDIAGDJ/GDIAGD1/GD0AGD1/GD0AGD1/GD0AGD1/GD0AGDJ/GDIAGDJ/GDIAGDJ/GDIAGDJ/GDIAGD1/GD0AGD1/GD0AGD1/GD0AGD1/GD0AGDJ/DDIADC1/DC0ADCZ/DCYADC1/DC0ADDJ/DDIADDZ/GDYAADJ/gRAyAAD/LwBNVHJrAAAAloEQmSp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAJCp/DCoAAP8vAA==");
});

app.listen(3000, function () {
  console.log('Example app listening on port 3000!');
});
